### ISSUE TITLE
Encode email wanting to update the database by itself

### ISSUE THREAD

**Issue by stromjoe** [barrelstrength/craft-sprout-encode-email#5]
After a recent Craft CMS update to version 2.7.4 we've noticed that the Sprout Encode Email plugin wants to do an database update by itself multiple times a day, causing the site in question to stop working until an admin user goes to the backend to finish the database update.
There are no errors regarding failed migrations or crashes in the logs.

Are there any known issues related to the plugin and the newest Craft 2 version?

- Craft version: 2.7.4
- PHP version: 5.6.39 (might be an issue)
- Plugins & versions: Sprout Encode Email 1.3.0

**Comment by BenParizek** [comment]
@stromjoe Is this still an issue? I think we got wrapped up in 3.1 updates and I overlooked follow up. There is no reason that Sprout Encode Email should be doing anything database related, including triggering an update unless Craft changed some behavior in how the getSchemaVersion method works.

We don't even have the getSchemaVersion method in our plugin so Craft has to be assuming the default value of that method should be creating the behavior you are seeing. Do you see any issues in the logs? Can you provide any screenshots that might give us any other insights?

One test we could do is have you add a getSchemaVersion method to the plugin and see if that gets Craft to stop behaving that way.

**Comment by BenParizek** [comment]
@stromjoe As we haven't heard back on this and haven't heard any other reports of it, I'm going to close this out. Feel free to reopen if you want to discuss further.
