### ISSUE TITLE
E-mails are hidden if not all cookies are allowed

### ISSUE THREAD

**Issue by sandissauka** [barrelstrength/craft-sprout-encode-email#8]
### Description (screenshots, logs, ...)
If only necessary cookies are allowed (we're using Cookiebot https://www.cookiebot.com), then e-mails are not shown. They only show up if only all cookies are allowed.

In the case of this plugin, no cookie is set with "Sprout Encode Email". Typically, we could add any cookie in the necessary section, but not in this case. In order to work with this plugin, we're asking you to do so.

### Additional info

- Craft version: 3.7.37
- PHP version: 7.3.27
- Database driver & version:  MySQL 5.7.33
- Plugins & versions: Sprout Encode Email 2.0.7

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by sandissauka** [comment]
@BenParizek & @brandonkelly ping 🛎

Let me know even if you don't plan to work on it. We'll fork and make changes ourselves.

**Comment by brandonkelly** [comment]
I’m not affiliated with Barrel Strength or this plugin, but the [readme](https://github.com/barrelstrength/craft-sprout-encode-email/blob/v2/README.md) looks like it has your answer:

> ## Status
>
> [![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)
>
> In an effort to reduce the number of packages we publicly maintain, Sprout Encode Email will not be migrated to Craft 4. If you'd like to take the helm or take responsibility over maintaining the repository please reach out: [sprout@barrelstrengthdesign.com](mailto:sprout@barrelstrengthdesign.com).

**Comment by sandissauka** [comment]
@brandonkelly, thanks, I see. Any intent for the Craft team to take it over, even integrate it?

**Comment by brandonkelly** [comment]
You’re welcome to [start a discussion](https://github.com/craftcms/cms/discussions/new?category=ideas) about it!
